appenders:
  my_stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S:%f)(local)} | {h({l})} | {f}:{L} | {m}{n}"
  my_file_logger:
    kind: rolling_file
    path: "logs/binance_data.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S:%f)(local)} | {h({l})} | {f}:{L} | {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 50000000kb
      roller:
        kind: fixed_window
        base: 1
        count: 1000000
        pattern: "logs/my{}.log"
root:
  level: info
  appenders:
    - my_stdout
    - my_file_logger